const firebase = require("firebase");
require("firebase/firestore");

firebase.initializeApp({
  apiKey: "AIzaSyDXHP95xunTSBO0U61PlNhOLjyjXmIVXRI",
  authDomain: "conpresp.firebaseapp.com",
  databaseURL: "https://conpresp.firebaseio.com",
  projectId: "conpresp",
  storageBucket: "conpresp.appspot.com",
  messagingSenderId: "493438146924",
  appId: "1:493438146924:web:7b8ba5f8aacb97b114fb49",
  measurementId: "G-RV1V75RE2Q",
});

var db = firebase.firestore();

var userCollections = [
  {
    ID: "21",
    CODIGO_LPP: "3792/161-021",
    PORCENTAJE: "79%",
    NUMERO: "021",
    GRUPO: " Centro/Mo",
    GLPPP: "Equipe Centro/Mooca",
    HORA_CADASTRO: "5/6/2019 15:46:04",
    LPP: "Andressa Germano",
    REVISAO: "Esthefania Regina S. Cardeal",
    RESOLUCAO: "37/92",
    NUMERO_BEM: "161",
    DENOMINACIONES: "Edifício Azevedo Soares ",
    COMPLEMENTARES: "Prédio Azevedo Soares -       ",
    NUMERO_BENS: "1",
    TIPO_BEM: "Imóvel",
    RECORTE_TEMATICO: "Edifícios Comerciais",
    PROPIEDADE: "Privada",
    USO_ORIGINAL_TERREO: "Comercial",
    USO_ORIGINAL_PAVIMENTOS: "Serviços",
    USO_ATUAL_TERREO: "Comercial",
    USO_ATUAL_PAVIMENTOS: "Serviços",
    USO_OBSERVACOES:
      "Uso original: Comércio + escritórios Uso atual: Comércio + serviços",
    CONPRESP: "Res. 37/92",
    RELACIONADAS_CONPRESP:
      "Res. 03/15, Res. 09/14, Res. 16/04, Res. 5/91 - imóvel Rua São Bento, Res. 6/91, Res. 11/91 e Res. 11/90.    ",
    CONDEPHAAT: "-",
    RELACIONADAS_CONDEPHAAT: "-    ",
    IPHAN: "-",
    RELACIONADAS_IPHAN: "-  ",
    APT: "T, ZEPEC BIR",
    TEO: "Não definido",
    T: "True",
    TICIP: "Não definido",
    ZEPEC_APC: "Não definido",
    ZEPEC_APP: "Não definido",
    ZEPEC_BIR: "Não definido",
    ZEPEC_AUE: "Não definido",
    TIPO_RUA: "RUA",
    TITULO: "Não definido",
    LOGRADOURO: "Bento",
    NUMERO_ATUAL: "45 a 51",
    ENDERECO_COMPLEMENTAR: "Não definido",
    DISTRITO: "Sé",
    PREFEITURA: "Sé",
    XSETOR: "x005",
    XQUADRA: "x003",
    XLOTE: "x0011",
    SETOR: "005",
    QUADRA: "003",
    LOTE: "0011",
    SQL: "0050030011",
    DAC: "9",
    COND: "-",
    TIPO_INMOVEL: "Não definido",
    LOGRADOURO2: "Não definido",
    NUMERO_ANTIGO: "45 a 51",
    AUTOR: "Eng. Archimedes de Barros Pimentel",
    CONSTRUTOR: "Sociedade Construtora Ltda.",
    PERIODO_CONSTRUCAO: "1932-1934",
    ESTILO_PRIMARIO: "Art Deco",
    ESTILO_SECUNDARIO: "Não definido",
    ESTILO_OBSERVACOES: "Não definido",
    TECNICA_PRIMARIA: "Concreto armado",
    TECNICA_SECUNDARIA: "Alvenaria de tijolos",
    TECNICA_OBSERVACOES: "Não definido",
    NUMERO_PAVIMENTOS: "5",
    OUTROS_PAVIMENTOS: "Térreo",
    OBSERVACOES_PAVIMENTOS:
      "Térreo + Sobreloja + 4 Pavimentos + 2 Pavimentos recuados",
    GRAU_TOMBAMENTO: "3",
    PRESERVACAO: "Alterado",
    CONSERVACAO: "Bom",
  },
  {
    ID: "22",
    CODIGO_LPP: "0591/064-022",
    PORCENTAJE: "58%",
    NUMERO: "022",
    GRUPO: "05",
    GLPPP: "Grupo 05",
    HORA_CADASTRO: "9/22/2017 19:18:05",
    LPP: "Virgínia Santos",
    REVISAO: "Sem autor",
    RESOLUCAO: "05/91",
    NUMERO_BEM: "064",
    DENOMINACIONES:
      "Conj.  de Edifícios do antigo Matadouro de Vila Mariana (Clementino)",
    COMPLEMENTARES: "Sem complementares",
    NUMERO_BENS: "Não definido",
    TIPO_BEM: "Imóvel",
    RECORTE_TEMATICO: "Edifícios Comerciais",
    PROPIEDADE: "Não definido",
    USO_ORIGINAL_TERREO: "Comercial",
    USO_ORIGINAL_PAVIMENTOS: "Não definido",
    USO_ATUAL_TERREO: "Institucional",
    USO_ATUAL_PAVIMENTOS: "Não definido",
    USO_OBSERVACOES: "Sem observações",
    CONPRESP: "Res. 05/91",
    RELACIONADAS_CONPRESP: "Res. 15/12    ",
    CONDEPHAAT: "RES. SC 07/85",
    RELACIONADAS_CONDEPHAAT: "-    ",
    IPHAN: "-",
    RELACIONADAS_IPHAN: "-  ",
    APT: "TEO, T",
    TEO: "Não definido",
    T: "Não definido",
    TICIP: "Não definido",
    ZEPEC_APC: "Não definido",
    ZEPEC_APP: "Não definido",
    ZEPEC_BIR: "Não definido",
    ZEPEC_AUE: "Não definido",
    TIPO_RUA: "LARGO",
    TITULO: "Não definido",
    LOGRADOURO: "Raul Cardoso",
    NUMERO_ATUAL: "133 - 207",
    ENDERECO_COMPLEMENTAR: "Não definido",
    DISTRITO: "Vila Mariana",
    PREFEITURA: "Vila Mariana",
    XSETOR: "x037",
    XQUADRA: "x048",
    XLOTE: "x0026",
    SETOR: "037",
    QUADRA: "048",
    LOTE: "0026",
    SQL: "0370480026",
    DAC: "0",
    COND: "-",
    TIPO_INMOVEL: "Não definido",
    LOGRADOURO2: "Não definido",
    NUMERO_ANTIGO: "-",
    AUTOR: " Engenheiro Alberto Kuhlmann",
    CONSTRUTOR: "Não definido",
    PERIODO_CONSTRUCAO: "Inaugurado - 21/06/1887",
    ESTILO_PRIMARIO: "Não definido",
    ESTILO_SECUNDARIO: "Não definido",
    ESTILO_OBSERVACOES: "Não definido",
    TECNICA_PRIMARIA: "Alvenaria de tijolos",
    TECNICA_SECUNDARIA: "Não definido",
    TECNICA_OBSERVACOES: "Não definido",
    NUMERO_PAVIMENTOS: "Não definido",
    OUTROS_PAVIMENTOS: "Não definido",
    OBSERVACOES_PAVIMENTOS: "Não definido",
    GRAU_TOMBAMENTO: "Não definido",
    PRESERVACAO: "Preservado",
    CONSERVACAO: "Bom",
  },
  {
    ID: "23",
    CODIGO_LPP: "3792/241-023",
    PORCENTAJE: "19%",
    NUMERO: "023",
    GRUPO: "06",
    GLPPP: "Grupo 06",
    HORA_CADASTRO: "11/9/2017 11:03:30",
    LPP: "Julia Selli",
    REVISAO: "Sem autor",
    RESOLUCAO: "37/92",
    NUMERO_BEM: "241",
    DENOMINACIONES: "37/92",
    COMPLEMENTARES: "Sem complementares",
    NUMERO_BENS: "1",
    TIPO_BEM: "Imóvel",
    RECORTE_TEMATICO: "Edifícios Comerciais",
    PROPIEDADE: "Não definido",
    USO_ORIGINAL_TERREO: "Não definido",
    USO_ORIGINAL_PAVIMENTOS: "Não definido",
    USO_ATUAL_TERREO: "Não definido",
    USO_ATUAL_PAVIMENTOS: "Não definido",
    USO_OBSERVACOES: "Sem observações",
    CONPRESP: "Res. 37/92",
    RELACIONADAS_CONPRESP: "    ",
    CONDEPHAAT: "Não definido",
    RELACIONADAS_CONDEPHAAT: "    ",
    IPHAN: "Não definido",
    RELACIONADAS_IPHAN: "  ",
    APT: "T",
    TEO: "Não definido",
    T: "Não definido",
    TICIP: "Não definido",
    ZEPEC_APC: "Não definido",
    ZEPEC_APP: "Não definido",
    ZEPEC_BIR: "Não definido",
    ZEPEC_AUE: "Não definido",
    TIPO_RUA: "Não definido",
    TITULO: "Não definido",
    LOGRADOURO: "Não definido",
    NUMERO_ATUAL: "Não definido",
    ENDERECO_COMPLEMENTAR: "Não definido",
    DISTRITO: "Não definido",
    PREFEITURA: "Não definido",
    XSETOR: "Não definido",
    XQUADRA: "Não definido",
    XLOTE: "Não definido",
    SETOR: "Não definido",
    QUADRA: "Não definido",
    LOTE: "Não definido",
    SQL: "Não definido",
    DAC: "Não definido",
    COND: "Não definido",
    TIPO_INMOVEL: "Não definido",
    LOGRADOURO2: "Não definido",
    NUMERO_ANTIGO: "Não definido",
    AUTOR: "Não definido",
    CONSTRUTOR: "Não definido",
    PERIODO_CONSTRUCAO: "Não definido",
    ESTILO_PRIMARIO: "Não definido",
    ESTILO_SECUNDARIO: "Não definido",
    ESTILO_OBSERVACOES: "Não definido",
    TECNICA_PRIMARIA: "Não definido",
    TECNICA_SECUNDARIA: "Não definido",
    TECNICA_OBSERVACOES: "Não definido",
    NUMERO_PAVIMENTOS: "Não definido",
    OUTROS_PAVIMENTOS: "Não definido",
    OBSERVACOES_PAVIMENTOS: "Não definido",
    GRAU_TOMBAMENTO: "Não definido",
    PRESERVACAO: "Não definido",
    CONSERVACAO: "Não definido",
  },
  {
    ID: "24",
    CODIGO_LPP: "3792/076-024",
    PORCENTAJE: "85%",
    NUMERO: "024",
    GRUPO: " Centro/Mo",
    GLPPP: "Equipe Centro/Mooca",
    HORA_CADASTRO: "5/6/2019 16:45:36",
    LPP: "Ariadni Aquino",
    REVISAO: "Sem autor",
    RESOLUCAO: "37/92",
    NUMERO_BEM: "076",
    DENOMINACIONES: "Hotel Dom José",
    COMPLEMENTARES:
      "Nao consta - Nao consta - Nao consta - Nao consta - Nao consta",
    NUMERO_BENS: "1",
    TIPO_BEM: "Imóvel",
    RECORTE_TEMATICO: "Edifícios de Uso Misto",
    PROPIEDADE: "Não definido",
    USO_ORIGINAL_TERREO: "Comercial",
    USO_ORIGINAL_PAVIMENTOS: "Outros",
    USO_ATUAL_TERREO: "Comercial",
    USO_ATUAL_PAVIMENTOS: "Outros",
    USO_OBSERVACOES: "Sem observações",
    CONPRESP: "Res. 37/92",
    RELACIONADAS_CONPRESP: "TEO Res. 05/91  Nao consta  Nao consta",
    CONDEPHAAT: "Res. SC 49/81",
    RELACIONADAS_CONDEPHAAT: "Proc. SC 24.507/86 - Nao consta - Nao consta",
    IPHAN: "Nao consta",
    RELACIONADAS_IPHAN: "Nao consta - Nao consta",
    APT: "TEO",
    TEO: "True",
    T: "Não definido",
    TICIP: "Não definido",
    ZEPEC_APC: "Não definido",
    ZEPEC_APP: "Não definido",
    ZEPEC_BIR: "True",
    ZEPEC_AUE: "Não definido",
    TIPO_RUA: "AVENIDA",
    TITULO: "SAO",
    LOGRADOURO: "Joao",
    NUMERO_ATUAL: "514",
    ENDERECO_COMPLEMENTAR: "Não definido",
    DISTRITO: "República",
    PREFEITURA: "Sé",
    XSETOR: "x001",
    XQUADRA: "x055",
    XLOTE: "x0007",
    SETOR: "001",
    QUADRA: "055",
    LOTE: "0007",
    SQL: "0010550007",
    DAC: "0",
    COND: "n/a",
    TIPO_INMOVEL: "AVENIDA",
    LOGRADOURO2: "Joao",
    NUMERO_ANTIGO: "514; 518",
    AUTOR: "Não identificado",
    CONSTRUTOR: "Não identificado",
    PERIODO_CONSTRUCAO: "1913",
    ESTILO_PRIMARIO: "Eclético",
    ESTILO_SECUNDARIO: "Neoclássico",
    ESTILO_OBSERVACOES: "Não definido",
    TECNICA_PRIMARIA: "Técnica Mista",
    TECNICA_SECUNDARIA: "Alvenaria de tijolos",
    TECNICA_OBSERVACOES: "Estrutura mista e vedação em alvenaria.",
    NUMERO_PAVIMENTOS: "3",
    OUTROS_PAVIMENTOS: "Térreo",
    OBSERVACOES_PAVIMENTOS: "Térreo + 3 pavimentos",
    GRAU_TOMBAMENTO: "NP - 3",
    PRESERVACAO: "Alterado",
    CONSERVACAO: "Precário",
  },
  {
    ID: "25",
    CODIGO_LPP: "3792/077-025",
    PORCENTAJE: "84%",
    NUMERO: "025",
    GRUPO: " Centro/Mo",
    GLPPP: "Equipe Centro/Mooca",
    HORA_CADASTRO: "11/4/2019 19:28:28",
    LPP: "Emily Cândido",
    REVISAO: "Sem autor",
    RESOLUCAO: "37/92",
    NUMERO_BEM: "077",
    DENOMINACIONES: "Edifício na Avenida São João",
    COMPLEMENTARES: "Hotel Cinelândia - N/C - N/C - N/C - N/C",
    NUMERO_BENS: "1",
    TIPO_BEM: "Imóvel",
    RECORTE_TEMATICO: "Edifícios Hoteleiros",
    PROPIEDADE: "Privada",
    USO_ORIGINAL_TERREO: "Serviços",
    USO_ORIGINAL_PAVIMENTOS: "Serviços",
    USO_ATUAL_TERREO: "Serviços",
    USO_ATUAL_PAVIMENTOS: "Serviços",
    USO_OBSERVACOES: "Hotel ",
    CONPRESP: "Res. 37/92",
    RELACIONADAS_CONPRESP: "TEO Res. 05/91  N/C  N/C",
    CONDEPHAAT: "Res. SC 49/81",
    RELACIONADAS_CONDEPHAAT: "Proc. SC 24.507/86 - N/C - N/C",
    IPHAN: "N/C",
    RELACIONADAS_IPHAN: "N/C - N/C",
    APT: "TEO",
    TEO: "True",
    T: "Não definido",
    TICIP: "Não definido",
    ZEPEC_APC: "Não definido",
    ZEPEC_APP: "Não definido",
    ZEPEC_BIR: "True",
    ZEPEC_AUE: "Não definido",
    TIPO_RUA: "AVENIDA",
    TITULO: "SAO",
    LOGRADOURO: "João",
    NUMERO_ATUAL: "526",
    ENDERECO_COMPLEMENTAR: "Não definido",
    DISTRITO: "República",
    PREFEITURA: "Sé",
    XSETOR: "x001",
    XQUADRA: "x055",
    XLOTE: "x0006",
    SETOR: "001",
    QUADRA: "055",
    LOTE: "0006",
    SQL: "0010550006",
    DAC: "2",
    COND: "n/a",
    TIPO_INMOVEL: "AVENIDA",
    LOGRADOURO2: "Joao",
    NUMERO_ANTIGO: "526; 530",
    AUTOR: "Desconhecido",
    CONSTRUTOR: "Desconhecido",
    PERIODO_CONSTRUCAO: "Desconhecido ",
    ESTILO_PRIMARIO: "Eclético",
    ESTILO_SECUNDARIO: "Eclético",
    ESTILO_OBSERVACOES: "Não definido",
    TECNICA_PRIMARIA: "Alvenaria de tijolos",
    TECNICA_SECUNDARIA: "Não definido",
    TECNICA_OBSERVACOES: "Não definido",
    NUMERO_PAVIMENTOS: "8",
    OUTROS_PAVIMENTOS: "Térreo",
    OBSERVACOES_PAVIMENTOS: "Não definido",
    GRAU_TOMBAMENTO: "NP - 3",
    PRESERVACAO: "Alterado",
    CONSERVACAO: "Bom",
  },
  {
    ID: "26",
    CODIGO_LPP: "0591/012-026",
    PORCENTAJE: "81%",
    NUMERO: "026",
    GRUPO: " Centro/Mo",
    GLPPP: "Equipe Centro/Mooca",
    HORA_CADASTRO: "4/28/2019 16:42:05",
    LPP: "Ligia Mezher Silva",
    REVISAO: "Aline Portella",
    RESOLUCAO: "05/91",
    NUMERO_BEM: "012",
    DENOMINACIONES: "Casa do Sítio Tatuapé - Casa Bandeirista do Tatuapé",
    COMPLEMENTARES: "Casa do Tatuapé -       ",
    NUMERO_BENS: "01",
    TIPO_BEM: "Imóvel",
    RECORTE_TEMATICO: "Edifícios Residenciais Unifamiliares",
    PROPIEDADE: "Pública Municipal",
    USO_ORIGINAL_TERREO: "Residencial",
    USO_ORIGINAL_PAVIMENTOS: "Não definido",
    USO_ATUAL_TERREO: "Outros",
    USO_ATUAL_PAVIMENTOS: "Outros",
    USO_OBSERVACOES: "É um centro cultural. ",
    CONPRESP: "Res. 05/91",
    RELACIONADAS_CONPRESP: "    ",
    CONDEPHAAT: "RES. SC S/N/74",
    RELACIONADAS_CONDEPHAAT: "    ",
    IPHAN: "PROC. 0353-T-51",
    RELACIONADAS_IPHAN: "  ",
    APT: "TEO, T, ZEPEC BIR",
    TEO: "True",
    T: "True",
    TICIP: "Não definido",
    ZEPEC_APC: "Não definido",
    ZEPEC_APP: "Não definido",
    ZEPEC_BIR: "True",
    ZEPEC_AUE: "Não definido",
    TIPO_RUA: "RUA",
    TITULO: "Não definido",
    LOGRADOURO: "Guabiju",
    NUMERO_ATUAL: "49",
    ENDERECO_COMPLEMENTAR: "Não definido",
    DISTRITO: "Tatuapé",
    PREFEITURA: "Mooca",
    XSETOR: "x062",
    XQUADRA: "x162",
    XLOTE: "x0023",
    SETOR: "062",
    QUADRA: "162",
    LOTE: "0023",
    SQL: "0621620023",
    DAC: "2",
    COND: "n/a",
    TIPO_INMOVEL: "RUA",
    LOGRADOURO2: "Guabiju",
    NUMERO_ANTIGO: "65",
    AUTOR: "Mathias Rodrigues da Silva",
    CONSTRUTOR: "Desconhecido",
    PERIODO_CONSTRUCAO: "Entre 1668 e 1698",
    ESTILO_PRIMARIO: "Bandeirista",
    ESTILO_SECUNDARIO: "Não definido",
    ESTILO_OBSERVACOES: "Não definido",
    TECNICA_PRIMARIA: "Taipa-de-pilão",
    TECNICA_SECUNDARIA: "Não definido",
    TECNICA_OBSERVACOES: "Não definido",
    NUMERO_PAVIMENTOS: "1",
    OUTROS_PAVIMENTOS: "Térreo",
    OBSERVACOES_PAVIMENTOS: "Casa Térrea",
    GRAU_TOMBAMENTO: "TOMBADO - PRESERVAÇÃO TOTAL",
    PRESERVACAO: "Preservado",
    CONSERVACAO: "Bom",
  },
  {
    ID: "27",
    CODIGO_LPP: "3792/162-027",
    PORCENTAJE: "73%",
    NUMERO: "027",
    GRUPO: " Vila Olím",
    GLPPP: "Equipe Vila Olímpia",
    HORA_CADASTRO: "11/25/2019 13:25:17",
    LPP: "Gyovanna Cerres",
    REVISAO: "Mayumi",
    RESOLUCAO: "37/92",
    NUMERO_BEM: "162",
    DENOMINACIONES: "Edifício Rua São Bento, 67.",
    COMPLEMENTARES: "Sem complementares",
    NUMERO_BENS: "1",
    TIPO_BEM: "Imóvel",
    RECORTE_TEMATICO: "Edifícios Comerciais",
    PROPIEDADE: "Privada",
    USO_ORIGINAL_TERREO: "Comercial",
    USO_ORIGINAL_PAVIMENTOS: "Outros",
    USO_ATUAL_TERREO: "Comercial",
    USO_ATUAL_PAVIMENTOS: "Comercial",
    USO_OBSERVACOES:
      "loja com depósito (Dr. Shape, suplementação alimentar e artigos esportivos)",
    CONPRESP: "Res. 37/92",
    RELACIONADAS_CONPRESP: "    ",
    CONDEPHAAT: "-",
    RELACIONADAS_CONDEPHAAT:
      "A.E. RES. SC 49/81 - A.E. RES. SC 27/84 - A.E. RES. SC S/N/75",
    IPHAN: "N/C",
    RELACIONADAS_IPHAN: "N/C - N/C",
    APT: "TEO, T, ZEPEC BIR",
    TEO: "Não definido",
    T: "Não definido",
    TICIP: "Não definido",
    ZEPEC_APC: "Não definido",
    ZEPEC_APP: "Não definido",
    ZEPEC_BIR: "Não definido",
    ZEPEC_AUE: "Não definido",
    TIPO_RUA: "RUA",
    TITULO: "Não definido",
    LOGRADOURO: "Bento",
    NUMERO_ATUAL: "67",
    ENDERECO_COMPLEMENTAR: "Não definido",
    DISTRITO: "Sé",
    PREFEITURA: "Sé",
    XSETOR: "x005",
    XQUADRA: "x003",
    XLOTE: "x0009",
    SETOR: "005",
    QUADRA: "003",
    LOTE: "0009",
    SQL: "0050030009",
    DAC: "7",
    COND: "- ",
    TIPO_INMOVEL: "Não definido",
    LOGRADOURO2: "Não definido",
    NUMERO_ANTIGO: "67",
    AUTOR: "Não definido",
    CONSTRUTOR: "Não definido",
    PERIODO_CONSTRUCAO: "1908",
    ESTILO_PRIMARIO: "Eclético",
    ESTILO_SECUNDARIO: "Não definido",
    ESTILO_OBSERVACOES: "Não definido",
    TECNICA_PRIMARIA: "Técnica Mista",
    TECNICA_SECUNDARIA: "Alvenaria de tijolos",
    TECNICA_OBSERVACOES: "Não definido",
    NUMERO_PAVIMENTOS: "2",
    OUTROS_PAVIMENTOS: "Térreo",
    OBSERVACOES_PAVIMENTOS: "Não definido",
    GRAU_TOMBAMENTO: "3",
    PRESERVACAO: "Alterado",
    CONSERVACAO: "Regular",
  },
  {
    ID: "28",
    CODIGO_LPP: "0591/065-028",
    PORCENTAJE: "61%",
    NUMERO: "028",
    GRUPO: "05",
    GLPPP: "Grupo 05",
    HORA_CADASTRO: "9/28/2017 21:35:37",
    LPP: "Virgínia Santos",
    REVISAO: "Sem autor",
    RESOLUCAO: "05/91",
    NUMERO_BEM: "065",
    DENOMINACIONES:
      "Antigo Grupo Escolar Rodrigues Alves - E.E.P.G Rodrigues Alves",
    COMPLEMENTARES: "Sem complementares",
    NUMERO_BENS: "1",
    TIPO_BEM: "Imóvel",
    RECORTE_TEMATICO: "Edifícios Escolares",
    PROPIEDADE: "Pública Estadual",
    USO_ORIGINAL_TERREO: "Institucional",
    USO_ORIGINAL_PAVIMENTOS: "Não definido",
    USO_ATUAL_TERREO: "Institucional",
    USO_ATUAL_PAVIMENTOS: "Não definido",
    USO_OBSERVACOES: "Sem observações",
    CONPRESP: "Res. 05/91",
    RELACIONADAS_CONPRESP: "Res. 19/92 - A.E. E.E.P.G. Rodrigues Alves.    ",
    CONDEPHAAT: "RES. SC 101/13",
    RELACIONADAS_CONDEPHAAT:
      "Res. SC 102/13 - Redefine a área envoltória da E.E.P.G. Rodrigues Alves;  Res. SC 21/85 - Grupo Escolar Rodrigues Alves.    ",
    IPHAN: "-",
    RELACIONADAS_IPHAN: "-  ",
    APT: "TEO, T, ZEPEC BIR",
    TEO: "Não definido",
    T: "Não definido",
    TICIP: "Não definido",
    ZEPEC_APC: "Não definido",
    ZEPEC_APP: "Não definido",
    ZEPEC_BIR: "Não definido",
    ZEPEC_AUE: "Não definido",
    TIPO_RUA: "AVENIDA",
    TITULO: "Não definido",
    LOGRADOURO: "Paulista",
    NUMERO_ATUAL: "227",
    ENDERECO_COMPLEMENTAR: "Não definido",
    DISTRITO: "Vila Mariana",
    PREFEITURA: "Vila Mariana",
    XSETOR: "x036",
    XQUADRA: "x009",
    XLOTE: "x0001",
    SETOR: "036",
    QUADRA: "009",
    LOTE: "0001",
    SQL: "0360090001",
    DAC: "3",
    COND: "-",
    TIPO_INMOVEL: "Não definido",
    LOGRADOURO2: "Não definido",
    NUMERO_ANTIGO: "227",
    AUTOR: "Arquiteto Ramos de Azevedo",
    CONSTRUTOR: "Não definido",
    PERIODO_CONSTRUCAO: "1917 - 1919",
    ESTILO_PRIMARIO: "Eclético",
    ESTILO_SECUNDARIO: "Não definido",
    ESTILO_OBSERVACOES: "Não definido",
    TECNICA_PRIMARIA: "Não definido",
    TECNICA_SECUNDARIA: "Não definido",
    TECNICA_OBSERVACOES: "Não definido",
    NUMERO_PAVIMENTOS: "2",
    OUTROS_PAVIMENTOS: "Não definido",
    OBSERVACOES_PAVIMENTOS: "Não definido",
    GRAU_TOMBAMENTO: "Não definido",
    PRESERVACAO: "Preservado",
    CONSERVACAO: "Bom",
  },
  {
    ID: "29",
    CODIGO_LPP: "0591/066-029",
    PORCENTAJE: "61%",
    NUMERO: "029",
    GRUPO: "05",
    GLPPP: "Grupo 05",
    HORA_CADASTRO: "9/28/2017 21:28:38",
    LPP: "Virgínia Santos",
    REVISAO: "Sem autor",
    RESOLUCAO: "05/91",
    NUMERO_BEM: "066",
    DENOMINACIONES: "Residências da Família Ramos de Azevedo - Imóvel 1",
    COMPLEMENTARES: "Sem complementares",
    NUMERO_BENS: "3",
    TIPO_BEM: "Imóvel",
    RECORTE_TEMATICO: "Edifícios Residenciais Unifamiliares",
    PROPIEDADE: "Privada",
    USO_ORIGINAL_TERREO: "Residencial",
    USO_ORIGINAL_PAVIMENTOS: "Não definido",
    USO_ATUAL_TERREO: "Institucional",
    USO_ATUAL_PAVIMENTOS: "Não definido",
    USO_OBSERVACOES: "Sem observações",
    CONPRESP: "Res. 05/91",
    RELACIONADAS_CONPRESP: "-    ",
    CONDEPHAAT: " RES. SC 20/85",
    RELACIONADAS_CONDEPHAAT: "-    ",
    IPHAN: "-",
    RELACIONADAS_IPHAN: "-  ",
    APT: "TEO, T, ZEPEC BIR",
    TEO: "Não definido",
    T: "Não definido",
    TICIP: "Não definido",
    ZEPEC_APC: "Não definido",
    ZEPEC_APP: "Não definido",
    ZEPEC_BIR: "Não definido",
    ZEPEC_AUE: "Não definido",
    TIPO_RUA: "RUA",
    TITULO: "Não definido",
    LOGRADOURO: " Pirapitingui",
    NUMERO_ATUAL: "111",
    ENDERECO_COMPLEMENTAR: "Não definido",
    DISTRITO: "Liberdade",
    PREFEITURA: "Sé",
    XSETOR: "x033",
    XQUADRA: "x017",
    XLOTE: "x0013",
    SETOR: "033",
    QUADRA: "017",
    LOTE: "0013",
    SQL: "0330170013",
    DAC: "6",
    COND: "-",
    TIPO_INMOVEL: "Não definido",
    LOGRADOURO2: "Não definido",
    NUMERO_ANTIGO: "111",
    AUTOR: "Arquiteto Ramos de Azevedo",
    CONSTRUTOR: "Não definido",
    PERIODO_CONSTRUCAO: "1891",
    ESTILO_PRIMARIO: "Não definido",
    ESTILO_SECUNDARIO: "Não definido",
    ESTILO_OBSERVACOES: "Não definido",
    TECNICA_PRIMARIA: "Alvenaria de tijolos",
    TECNICA_SECUNDARIA: "Não definido",
    TECNICA_OBSERVACOES: "Não definido",
    NUMERO_PAVIMENTOS: "2",
    OUTROS_PAVIMENTOS: "Não definido",
    OBSERVACOES_PAVIMENTOS: "Não definido",
    GRAU_TOMBAMENTO: "Não definido",
    PRESERVACAO: "Preservado",
    CONSERVACAO: "Bom",
  },
];

userCollections.forEach(function (obj) {
  db.collection("conpresp_v1").add({
    ID: obj.ID,
    CODIGO_LPP: obj.CODIGO_LPP,
    PORCENTAJE: obj.PORCENTAJE,
    NUMERO: obj.NUMERO,
    GRUPO: obj.GRUPO,
    GLPPP: obj.GLPPP,
    HORA_CADASTRO: obj.HORA_CADASTRO,
    LPP: obj.LPP,
    REVISAO: obj.REVISAO,
    RESOLUCAO: obj.RESOLUCAO,
    NUMERO_BEM: obj.NUMERO_BEM,
    DENOMINACIONES: obj.DENOMINACIONES,
    COMPLEMENTARES: obj.COMPLEMENTARES,
    NUMERO_BENS: obj.NUMERO_BENS,
    TIPO_BEM: obj.TIPO_BEM,
    RECORTE_TEMATICO: obj.RECORTE_TEMATICO,
    PROPIEDADE: obj.PROPIEDADE,
    USO_ORIGINAL_TERREO: obj.USO_ORIGINAL_TERREO,
    USO_ORIGINAL_PAVIMENTOS: obj.USO_ORIGINAL_PAVIMENTOS,
    USO_ATUAL_TERREO: obj.USO_ATUAL_TERREO, //HERE
    USO_ATUAL_PAVIMENTOS: obj.USO_ATUAL_PAVIMENTOS,
    USO_OBSERVACOES: obj.USO_OBSERVACOES,
    CONPRESP: obj.CONPRESP,
    RELACIONADAS_CONPRESP: obj.RELACIONADAS_CONPRESP,
    CONDEPHAAT: obj.CONDEPHAAT,
    RELACIONADAS_CONDEPHAAT: obj.RELACIONADAS_CONDEPHAAT,
    IPHAN: obj.IPHAN,
    RELACIONADAS_IPHAN: obj.RELACIONADAS_IPHAN,
    APT: obj.APT,
    TEO: obj.TEO,
    T: obj.T,
    TICIP: obj.TICIP,
    ZEPEC_APC: obj.ZEPEC_APC,
    ZEPEC_APP: obj.ZEPEC_APP,
    ZEPEC_BIR: obj.ZEPEC_BIR,
    ZEPEC_AUE: obj.ZEPEC_AUE,
    TIPO_RUA: obj.TIPO_RUA,
    TITULO: obj.TITULO,
    LOGRADOURO: obj.LOGRADOURO,
    NUMERO_ATUAL: obj.NUMERO_ATUAL,
    ENDERECO_COMPLEMENTAR: obj.ENDERECO_COMPLEMENTAR,
    DISTRITO: obj.DISTRITO,
    PREFEITURA: obj.PREFEITURA,
    XSETOR: obj.XSETOR,
    XQUADRA: obj.XQUADRA,
    XLOTE: obj.XLOTE,
    SETOR: obj.SETOR,
    QUADRA: obj.QUADRA,
    LOTE: obj.LOTE,
    SQL: obj.SQL,
    DAC: obj.DAC,
    COND: obj.COND,
    TIPO_INMOVEL: obj.TIPO_INMOVEL,
    LOGRADOURO2: obj.LOGRADOURO2,
    NUMERO_ANTIGO: obj.NUMERO_ANTIGO,
    AUTOR: obj.AUTOR,
    CONSTRUTOR: obj.CONSTRUTOR,
    PERIODO_CONSTRUCAO: obj.PERIODO_CONSTRUCAO,
    ESTILO_PRIMARIO: obj.ESTILO_PRIMARIO,
    ESTILO_SECUNDARIO: obj.ESTILO_SECUNDARIO,
    ESTILO_OBSERVACOES: obj.ESTILO_OBSERVACOES,
    TECNICA_PRIMARIA: obj.TECNICA_PRIMARIA,
    TECNICA_SECUNDARIA: obj.TECNICA_SECUNDARIA,
    TECNICA_OBSERVACOES: obj.TECNICA_OBSERVACOES,
    NUMERO_PAVIMENTOS: obj.NUMERO_PAVIMENTOS,
    OUTROS_PAVIMENTOS: obj.OUTROS_PAVIMENTOS,
    OBSERVACOES_PAVIMENTOS: obj.OBSERVACOES_PAVIMENTOS,
    GRAU_TOMBAMENTO: obj.GRAU_TOMBAMENTO,
    PRESERVACAO: obj.PRESERVACAO,
    CONSERVACAO: obj.CONSERVACAO,
  });
});
